package gwent

var AllCards = []Card{
	Card{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "geralt-of-rivia",
		DisplayName: "Geralt of Rivia",
		Strength:    15,
		Effects:     []Effect{Hero},
		Image:       "Geralt-of-Rivia-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "cirilla-fiona-elen-riannon",
		DisplayName: "Cirilla Fiona Elen Riannon",
		Strength:    15,
		Effects:     []Effect{Hero},
		Image:       "Cirilla-Fiona-Elen-Riannon-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "vesemir",
		DisplayName: "Vesemir",
		Strength:    6,
		Effects:     []Effect{},
		Image:       "Vesemir-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         RangedCombat,
		Name:        "yennefer-of-vengerberg",
		DisplayName: "Yennefer of Vengerberg",
		Strength:    7,
		Effects:     []Effect{Medic, Hero},
		Image:       "Yennefer-of-Vengerberg-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "triss-merigold",
		DisplayName: "Triss Merigold",
		Strength:    7,
		Effects:     []Effect{Hero},
		Image:       "Triss-Merigold-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "dandelion",
		DisplayName: "Dandelion",
		Strength:    2,
		Effects:     []Effect{MoraleBoost},
		Image:       "Dandelion-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "zoltan-chivay",
		DisplayName: "Zoltan Chivay",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Zoltan-Chivay-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "emiel-regis-rohellec-terzieff",
		DisplayName: "Emiel Regis Rohellec Terzieff",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Emiel-Regis-Rohellec-Terzieff-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "villentretenmerth",
		DisplayName: "Villentretenmerth",
		Strength:    7,
		Effects:     []Effect{Scorch},
		Image:       "Villentrerenmerth-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "avallac’h",
		DisplayName: "Avallac’h",
		Strength:    0,
		Effects:     []Effect{Spy, Hero},
		Image:       "Avallach-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Special,
		Name:        "decoy",
		DisplayName: "Decoy",
		Strength:    0,
		Effects:     []Effect{Decoy},
		Image:       "Decoy-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Special,
		Name:        "decoy",
		DisplayName: "Decoy",
		Strength:    0,
		Effects:     []Effect{Decoy},
		Image:       "Decoy-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Special,
		Name:        "decoy",
		DisplayName: "Decoy",
		Strength:    0,
		Effects:     []Effect{Decoy},
		Image:       "Decoy-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Special,
		Name:        "commander’s-horn",
		DisplayName: "Commander’s Horn",
		Strength:    0,
		Effects:     []Effect{MoraleBoost},
		Image:       "Commanders-horn-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Special,
		Name:        "commander’s-horn",
		DisplayName: "Commander’s Horn",
		Strength:    0,
		Effects:     []Effect{MoraleBoost},
		Image:       "Commanders-horn-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Special,
		Name:        "commander’s-horn",
		DisplayName: "Commander’s Horn",
		Strength:    0,
		Effects:     []Effect{MoraleBoost},
		Image:       "Commanders-horn-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Special,
		Name:        "scorch",
		DisplayName: "Scorch",
		Strength:    0,
		Effects:     []Effect{Scorch},
		Image:       "Scorch-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Special,
		Name:        "scorch",
		DisplayName: "Scorch",
		Strength:    0,
		Effects:     []Effect{Scorch},
		Image:       "Scorch-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Special,
		Name:        "scorch",
		DisplayName: "Scorch",
		Strength:    0,
		Effects:     []Effect{Scorch},
		Image:       "Scorch-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "biting-frost",
		DisplayName: "Biting Frost",
		Strength:    0,
		Effects:     []Effect{BitingFrost},
		Image:       "Biting-Frost-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "biting-frost",
		DisplayName: "Biting Frost",
		Strength:    0,
		Effects:     []Effect{BitingFrost},
		Image:       "Biting-Frost-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "biting-frost",
		DisplayName: "Biting Frost",
		Strength:    0,
		Effects:     []Effect{BitingFrost},
		Image:       "Biting-Frost-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "impenetrable-fog",
		DisplayName: "Impenetrable Fog",
		Strength:    0,
		Effects:     []Effect{ImpenetrableFog},
		Image:       "Impenetrable-fog-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "impenetrable-fog",
		DisplayName: "Impenetrable Fog",
		Strength:    0,
		Effects:     []Effect{ImpenetrableFog},
		Image:       "Impenetrable-fog-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "impenetrable-fog",
		DisplayName: "Impenetrable Fog",
		Strength:    0,
		Effects:     []Effect{ImpenetrableFog},
		Image:       "Impenetrable-fog-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "torrential-rain",
		DisplayName: "Torrential Rain",
		Strength:    0,
		Effects:     []Effect{TorrentialRain},
		Image:       "Torrential-rain-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "torrential-rain",
		DisplayName: "Torrential Rain",
		Strength:    0,
		Effects:     []Effect{TorrentialRain},
		Image:       "Torrential-rain-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "torrential-rain",
		DisplayName: "Torrential Rain",
		Strength:    0,
		Effects:     []Effect{TorrentialRain},
		Image:       "Torrential-rain-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "clear-weather",
		DisplayName: "Clear Weather",
		Strength:    0,
		Effects:     []Effect{ClearWeather},
		Image:       "Clear-weather-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "clear-weather",
		DisplayName: "Clear Weather",
		Strength:    0,
		Effects:     []Effect{ClearWeather},
		Image:       "Clear-weather-gwent-card.jpg",
	},
	Card{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "clear-weather",
		DisplayName: "Clear Weather",
		Strength:    0,
		Effects:     []Effect{ClearWeather},
		Image:       "Clear-weather-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "vernon-roche",
		DisplayName: "Vernon Roche",
		Strength:    10,
		Effects:     []Effect{Hero},
		Image:       "Vernon-Roche-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "john-natalis",
		DisplayName: "John Natalis",
		Strength:    10,
		Effects:     []Effect{Hero},
		Image:       "John-Natalis-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "esterad-thyssen",
		DisplayName: "Esterad Thyssen",
		Strength:    10,
		Effects:     []Effect{Hero},
		Image:       "Esterad-Thyssen-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         RangedCombat,
		Name:        "philippa-eilhart",
		DisplayName: "Philippa Eilhart",
		Strength:    10,
		Effects:     []Effect{Hero},
		Image:       "Philippa-Eilhart-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "thaler",
		DisplayName: "Thaler",
		Strength:    1,
		Effects:     []Effect{Spy},
		Image:       "Thaler-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "ves",
		DisplayName: "Ves",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Ves-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "siegfried-of-denesle",
		DisplayName: "Siegfried of Denesle",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Siegfried-of-Denesle-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "yarpen-zigrin",
		DisplayName: "Yarpen Zigrin",
		Strength:    2,
		Effects:     []Effect{},
		Image:       "Yarpen-Zigrin-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "sigismund-dijkstra",
		DisplayName: "Sigismund Dijkstra",
		Strength:    4,
		Effects:     []Effect{Spy},
		Image:       "Sigismund-Dijkstra-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         RangedCombat,
		Name:        "keira-metz",
		DisplayName: "Keira Metz",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Keira-Metz-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         RangedCombat,
		Name:        "sile-de-tansarville",
		DisplayName: "Síle de Tansarville",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Sile-de-Tansarville-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "sabrina-glevissig",
		DisplayName: "Sabrina Glevissig",
		Strength:    4,
		Effects:     []Effect{},
		Image:       "Sabrina-Glevissig-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "sheldon-skaggs",
		DisplayName: "Sheldon Skaggs",
		Strength:    4,
		Effects:     []Effect{},
		Image:       "Sheldon-Skaggs-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "dethmold",
		DisplayName: "Dethmold",
		Strength:    6,
		Effects:     []Effect{},
		Image:       "Dethmold-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "prince-stennis",
		DisplayName: "Prince Stennis",
		Strength:    5,
		Effects:     []Effect{Spy},
		Image:       "Prince-Stennis-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "trebuchet",
		DisplayName: "Trebuchet",
		Strength:    6,
		Effects:     []Effect{},
		Image:       "Trebuchet-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "trebuchet",
		DisplayName: "Trebuchet",
		Strength:    6,
		Effects:     []Effect{},
		Image:       "Trebuchet-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "poor-f*cking-infantry",
		DisplayName: "Poor F*cking Infantry",
		Strength:    1,
		Effects:     []Effect{TightBond},
		Image:       "Poor-Fucking-Infantry-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "poor-f*cking-infantry",
		DisplayName: "Poor F*cking Infantry",
		Strength:    1,
		Effects:     []Effect{TightBond},
		Image:       "Poor-Fucking-Infantry-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "poor-f*cking-infantry",
		DisplayName: "Poor F*cking Infantry",
		Strength:    1,
		Effects:     []Effect{TightBond},
		Image:       "Poor-Fucking-Infantry-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         RangedCombat,
		Name:        "crinfrid-reavers-dragon-hunter",
		DisplayName: "Crinfrid Reavers Dragon Hunter",
		Strength:    5,
		Effects:     []Effect{TightBond},
		Image:       "Crinfrid-Reavers-Dragon-Hunter-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         RangedCombat,
		Name:        "crinfrid-reavers-dragon-hunter",
		DisplayName: "Crinfrid Reavers Dragon Hunter",
		Strength:    5,
		Effects:     []Effect{TightBond},
		Image:       "Crinfrid-Reavers-Dragon-Hunter-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         RangedCombat,
		Name:        "crinfrid-reavers-dragon-hunter",
		DisplayName: "Crinfrid Reavers Dragon Hunter",
		Strength:    5,
		Effects:     []Effect{TightBond},
		Image:       "Crinfrid-Reavers-Dragon-Hunter-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "redanian-foot-soldier",
		DisplayName: "Redanian Foot Soldier",
		Strength:    1,
		Effects:     []Effect{},
		Image:       "Redanian-Foot-Soldier-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "redanian-foot-soldier",
		DisplayName: "Redanian Foot Soldier",
		Strength:    1,
		Effects:     []Effect{},
		Image:       "Redanian-Foot-Soldier-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "catapult",
		DisplayName: "Catapult",
		Strength:    8,
		Effects:     []Effect{TightBond},
		Image:       "Catapult-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "catapult",
		DisplayName: "Catapult",
		Strength:    8,
		Effects:     []Effect{TightBond},
		Image:       "Catapult-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "ballista",
		DisplayName: "Ballista",
		Strength:    6,
		Effects:     []Effect{},
		Image:       "Ballista-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "ballista",
		DisplayName: "Ballista",
		Strength:    6,
		Effects:     []Effect{},
		Image:       "Ballista-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "kaedweni-siege-expert",
		DisplayName: "Kaedweni Siege Expert",
		Strength:    1,
		Effects:     []Effect{MoraleBoost},
		Image:       "Keadweni-Siege-Expert-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "kaedweni-siege-expert",
		DisplayName: "Kaedweni Siege Expert",
		Strength:    1,
		Effects:     []Effect{MoraleBoost},
		Image:       "Keadweni-Siege-Expert-2-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "kaedweni-siege-expert",
		DisplayName: "Kaedweni Siege Expert",
		Strength:    1,
		Effects:     []Effect{MoraleBoost},
		Image:       "Keadweni-Siege-Expert-3-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "blue-stripes-commando",
		DisplayName: "Blue Stripes Commando",
		Strength:    4,
		Effects:     []Effect{TightBond},
		Image:       "Blue-Stripes-Commando-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "blue-stripes-commando",
		DisplayName: "Blue Stripes Commando",
		Strength:    4,
		Effects:     []Effect{TightBond},
		Image:       "Blue-Stripes-Commando-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "blue-stripes-commando",
		DisplayName: "Blue Stripes Commando",
		Strength:    4,
		Effects:     []Effect{TightBond},
		Image:       "Blue-Stripes-Commando-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "siege-tower",
		DisplayName: "Siege Tower",
		Strength:    6,
		Effects:     []Effect{},
		Image:       "Siege-Tower-gwent-card.jpg",
	},
	Card{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "dun-banner-medic",
		DisplayName: "Dun Banner Medic",
		Strength:    5,
		Effects:     []Effect{Medic},
		Image:       "Dun-Banner-Medic-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "letho-of-gulet",
		DisplayName: "Letho of Gulet",
		Strength:    10,
		Effects:     []Effect{Hero},
		Image:       "Letho-of-Gulet-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "menno-coehoorn",
		DisplayName: "Menno Coehoorn",
		Strength:    10,
		Effects:     []Effect{Hero},
		Image:       "Menno-Coehoorn-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         Siege,
		Name:        "morvran-voorhis",
		DisplayName: "Morvran Voorhis",
		Strength:    10,
		Effects:     []Effect{Hero},
		Image:       "Morvran-Voorhis-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "tibor-eggebracht",
		DisplayName: "Tibor Eggebracht",
		Strength:    10,
		Effects:     []Effect{Hero},
		Image:       "Tibor-Eggebracht-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "albrich",
		DisplayName: "Albrich",
		Strength:    2,
		Effects:     []Effect{},
		Image:       "Albrich-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "assire-var-anahid",
		DisplayName: "Assire var Anahid",
		Strength:    6,
		Effects:     []Effect{},
		Image:       "Assire-var-Anahid-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "cynthia",
		DisplayName: "Cynthia",
		Strength:    4,
		Effects:     []Effect{},
		Image:       "Cynthia-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "fringilla-vigo",
		DisplayName: "Fringilla Vigo",
		Strength:    6,
		Effects:     []Effect{},
		Image:       "Fringilla-Vigo-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "morteisen",
		DisplayName: "Morteisen",
		Strength:    3,
		Effects:     []Effect{},
		Image:       "Morteisen-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "rainfarn",
		DisplayName: "Rainfarn",
		Strength:    4,
		Effects:     []Effect{},
		Image:       "Rainfarn-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "renuald-aep-matsen",
		DisplayName: "Renuald aep Matsen",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Renuald-aep-Matsen-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         Siege,
		Name:        "rotten-mangonel",
		DisplayName: "Rotten Mangonel",
		Strength:    3,
		Effects:     []Effect{},
		Image:       "Rotten-Mangonel-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "shilard-fitz-oesterlen",
		DisplayName: "Shilard Fitz-Oesterlen",
		Strength:    7,
		Effects:     []Effect{Spy},
		Image:       "Shilard-Fitz-Oesterlen-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "stefan-skellen",
		DisplayName: "Stefan Skellen",
		Strength:    9,
		Effects:     []Effect{Spy},
		Image:       "Stefan-Skellen-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "sweers",
		DisplayName: "Sweers",
		Strength:    2,
		Effects:     []Effect{},
		Image:       "Sweers-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "vanhemar",
		DisplayName: "Vanhemar",
		Strength:    4,
		Effects:     []Effect{},
		Image:       "Vanhemar-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "vattier-de-rideaux",
		DisplayName: "Vattier de Rideaux",
		Strength:    4,
		Effects:     []Effect{Spy},
		Image:       "Vattier-de-Rideaux-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "vreemde",
		DisplayName: "Vreemde",
		Strength:    2,
		Effects:     []Effect{},
		Image:       "Vreemde-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "cahir-mawr-dyffryn-aep-ceallach",
		DisplayName: "Cahir Mawr Dyffryn aep Ceallach",
		Strength:    6,
		Effects:     []Effect{},
		Image:       "Cahir-Mawr-Dyffryn-aep-Ceallach-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "puttkammer",
		DisplayName: "Puttkammer",
		Strength:    3,
		Effects:     []Effect{},
		Image:       "Puttkammer-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "etolian-auxiliary-archers",
		DisplayName: "Etolian Auxiliary Archers",
		Strength:    1,
		Effects:     []Effect{Medic},
		Image:       "Etolian-Auxiliary-Archers-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "etolian-auxiliary-archers",
		DisplayName: "Etolian Auxiliary Archers",
		Strength:    1,
		Effects:     []Effect{Medic},
		Image:       "Etolian-Auxiliary-Archers-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "black-infantry-archer",
		DisplayName: "Black Infantry Archer",
		Strength:    10,
		Effects:     []Effect{},
		Image:       "Black-Infantry-Archer-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         Siege,
		Name:        "siege-technican",
		DisplayName: "Siege Technican",
		Strength:    0,
		Effects:     []Effect{Medic},
		Image:       "Siege-Technican-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "black-infantry-archer",
		DisplayName: "Black Infantry Archer",
		Strength:    10,
		Effects:     []Effect{},
		Image:       "Black-Infantry-Archer-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         Siege,
		Name:        "heavy-zerrikanian-fire-scorpion",
		DisplayName: "Heavy Zerrikanian Fire Scorpion",
		Strength:    10,
		Effects:     []Effect{},
		Image:       "Heavy-Zerrikanian-Fire-Scorpion-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         Siege,
		Name:        "zerrikanian-fire-scorpion",
		DisplayName: "Zerrikanian Fire Scorpion",
		Strength:    10,
		Effects:     []Effect{},
		Image:       "Zerrikanian-Fire-Scorpion-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "impera-brigade",
		DisplayName: "Impera Brigade",
		Strength:    3,
		Effects:     []Effect{TightBond},
		Image:       "Impera-Brigade-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "impera-brigade",
		DisplayName: "Impera Brigade",
		Strength:    3,
		Effects:     []Effect{TightBond},
		Image:       "Impera-Brigade-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "impera-brigade",
		DisplayName: "Impera Brigade",
		Strength:    3,
		Effects:     []Effect{TightBond},
		Image:       "Impera-Brigade-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "impera-brigade",
		DisplayName: "Impera Brigade",
		Strength:    3,
		Effects:     []Effect{TightBond},
		Image:       "Impera-Brigade-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "nausicaa-cavalry-brigade",
		DisplayName: "Nausicaa Cavalry Brigade",
		Strength:    2,
		Effects:     []Effect{TightBond},
		Image:       "Nausicaa-Cavalry-Brigade-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "nausicaa-cavalry-brigade",
		DisplayName: "Nausicaa Cavalry Brigade",
		Strength:    2,
		Effects:     []Effect{TightBond},
		Image:       "Nausicaa-Cavalry-Brigade-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "nausicaa-cavalry-brigade",
		DisplayName: "Nausicaa Cavalry Brigade",
		Strength:    2,
		Effects:     []Effect{TightBond},
		Image:       "Nausicaa-Cavalry-Brigade-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         Siege,
		Name:        "siege-engineer",
		DisplayName: "Siege Engineer",
		Strength:    6,
		Effects:     []Effect{},
		Image:       "Siege-Engineer-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "young-emissary",
		DisplayName: "Young Emissary",
		Strength:    5,
		Effects:     []Effect{TightBond},
		Image:       "Young-Emissary-gwent-card.jpg",
	},
	Card{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "young-emissary",
		DisplayName: "Young Emissary",
		Strength:    5,
		Effects:     []Effect{TightBond},
		Image:       "Young-Emissary-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "eithne",
		DisplayName: "Eithné",
		Strength:    10,
		Effects:     []Effect{Hero},
		Image:       "Eithne-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "saesenthessis",
		DisplayName: "Saesenthessis",
		Strength:    10,
		Effects:     []Effect{Hero},
		Image:       "Seasenthessis-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "isengrim-faoiltiarna",
		DisplayName: "Isengrim Faoiltiarna",
		Strength:    10,
		Effects:     []Effect{MoraleBoost},
		Image:       "Isengrim-Faolitarna-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "iorveth",
		DisplayName: "Iorveth",
		Strength:    10,
		Effects:     []Effect{Hero},
		Image:       "Iorveth-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "dennis-cranmer",
		DisplayName: "Dennis Cranmer",
		Strength:    6,
		Effects:     []Effect{},
		Image:       "Dennis-Cranmer-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "milva",
		DisplayName: "Milva",
		Strength:    10,
		Effects:     []Effect{MoraleBoost},
		Image:       "Milva-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "ida-emean",
		DisplayName: "Ida Emean",
		Strength:    6,
		Effects:     []Effect{},
		Image:       "Ida-Emean-aep-Sivney-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "filavandrel",
		DisplayName: "Filavandrel",
		Strength:    6,
		Effects:     []Effect{Agile},
		Image:       "Filavandrel-aen-Fidhail-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "yaevinn",
		DisplayName: "Yaevinn",
		Strength:    6,
		Effects:     []Effect{Agile},
		Image:       "Yaevinn-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "toruviel",
		DisplayName: "Toruviel",
		Strength:    2,
		Effects:     []Effect{},
		Image:       "Toruviel-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "riordain",
		DisplayName: "Riordain",
		Strength:    1,
		Effects:     []Effect{},
		Image:       "Riordain-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "ciaran-aep-easnillien",
		DisplayName: "Ciaran aep Easnillien",
		Strength:    3,
		Effects:     []Effect{Agile},
		Image:       "Ciaran-aep-Easnillien-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "barclay-els",
		DisplayName: "Barclay Els",
		Strength:    6,
		Effects:     []Effect{Agile},
		Image:       "Barclay-Els-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "havekar-healer",
		DisplayName: "Havekar Healer",
		Strength:    0,
		Effects:     []Effect{Medic},
		Image:       "Havekar-Healer-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "havekar-healer",
		DisplayName: "Havekar Healer",
		Strength:    0,
		Effects:     []Effect{Medic},
		Image:       "Havekar-Healer-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "havekar-healer",
		DisplayName: "Havekar Healer",
		Strength:    0,
		Effects:     []Effect{Medic},
		Image:       "Havekar-Healer-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "vrihedd-brigade-veteran",
		DisplayName: "Vrihedd Brigade Veteran",
		Strength:    5,
		Effects:     []Effect{Agile},
		Image:       "Vrihedd-Brigade-Veteran-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "vrihedd-brigade-veteran",
		DisplayName: "Vrihedd Brigade Veteran",
		Strength:    5,
		Effects:     []Effect{Agile},
		Image:       "Vrihedd-Brigade-Veteran-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "dol-blathanna-archer",
		DisplayName: "Dol Blathanna Archer",
		Strength:    6,
		Effects:     []Effect{Agile},
		Image:       "Dol-Blathanna-Archer-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "dol-blathanna-scout",
		DisplayName: "Dol Blathanna Scout",
		Strength:    6,
		Effects:     []Effect{Agile},
		Image:       "Dol-Blathanna-Scout-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "dol-blathanna-scout",
		DisplayName: "Dol Blathanna Scout",
		Strength:    6,
		Effects:     []Effect{Agile},
		Image:       "Dol-Blathanna-Scout-2-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "dwarf-skirmisher",
		DisplayName: "Dwarf Skirmisher",
		Strength:    3,
		Effects:     []Effect{Muster},
		Image:       "Dwarven-Skirmisher-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "dwarf-skirmisher",
		DisplayName: "Dwarf Skirmisher",
		Strength:    3,
		Effects:     []Effect{Muster},
		Image:       "Dwarven-Skirmisher-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "dwarf-skirmisher",
		DisplayName: "Dwarf Skirmisher",
		Strength:    3,
		Effects:     []Effect{Muster},
		Image:       "Dwarven-Skirmisher-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "mahakaman-defender",
		DisplayName: "Mahakaman Defender",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Mahakaman-Defender-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "mahakaman-defender",
		DisplayName: "Mahakaman Defender",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Mahakaman-Defender-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "mahakaman-defender",
		DisplayName: "Mahakaman Defender",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Mahakaman-Defender-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "mahakaman-defender",
		DisplayName: "Mahakaman Defender",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Mahakaman-Defender-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "mahakaman-defender",
		DisplayName: "Mahakaman Defender",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Mahakaman-Defender-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "elven-skirmisher",
		DisplayName: "Elven Skirmisher",
		Strength:    2,
		Effects:     []Effect{Muster},
		Image:       "Elven-Skirmisher-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "elven-skirmisher",
		DisplayName: "Elven Skirmisher",
		Strength:    2,
		Effects:     []Effect{Muster},
		Image:       "Elven-Skirmisher-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "elven-skirmisher",
		DisplayName: "Elven Skirmisher",
		Strength:    2,
		Effects:     []Effect{Muster},
		Image:       "Elven-Skirmisher-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "vrihedd-cadet",
		DisplayName: "Vrihedd Cadet",
		Strength:    4,
		Effects:     []Effect{},
		Image:       "Vrihedd-Brigade-Veteran-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "dol-blathanna-archer",
		DisplayName: "Dol Blathanna Archer",
		Strength:    4,
		Effects:     []Effect{},
		Image:       "Dol-Blathanna-Archer-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "havekar-smuggler",
		DisplayName: "Havekar Smuggler",
		Strength:    5,
		Effects:     []Effect{Muster},
		Image:       "Havekar-Smuggler-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "havekar-smuggler",
		DisplayName: "Havekar Smuggler",
		Strength:    5,
		Effects:     []Effect{Muster},
		Image:       "Havekar-Smuggler-gwent-card.jpg",
	},
	Card{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "havekar-smuggler",
		DisplayName: "Havekar Smuggler",
		Strength:    5,
		Effects:     []Effect{Muster},
		Image:       "Havekar-Smuggler-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "draug",
		DisplayName: "Draug",
		Strength:    10,
		Effects:     []Effect{Hero},
		Image:       "Draug-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         Special,
		Name:        "kayran",
		DisplayName: "Kayran",
		Strength:    18,
		Effects:     []Effect{MoraleBoost, Agile, Hero},
		Image:       "Kayran-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "imlerith",
		DisplayName: "Imlerith",
		Strength:    10,
		Effects:     []Effect{Hero},
		Image:       "Imlerith-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         RangedCombat,
		Name:        "leshen",
		DisplayName: "Leshen",
		Strength:    10,
		Effects:     []Effect{Hero},
		Image:       "Leshen-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "forktail",
		DisplayName: "Forktail",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Forktail-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         Siege,
		Name:        "earth-elemental",
		DisplayName: "Earth Elemental",
		Strength:    6,
		Effects:     []Effect{},
		Image:       "Earth-Elemental-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "fiend",
		DisplayName: "Fiend",
		Strength:    6,
		Effects:     []Effect{},
		Image:       "Fiend-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "plague-maiden",
		DisplayName: "Plague Maiden",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Plague-Maiden-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "griffin",
		DisplayName: "Griffin",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Griffin-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "werewolf",
		DisplayName: "Werewolf",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Werewolf-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "botchling",
		DisplayName: "Botchling",
		Strength:    4,
		Effects:     []Effect{},
		Image:       "Botchling-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "frightener",
		DisplayName: "Frightener",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Frightener-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         Siege,
		Name:        "ice-giant",
		DisplayName: "Ice Giant",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Ice-Giant-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         RangedCombat,
		Name:        "endrega",
		DisplayName: "Endrega",
		Strength:    2,
		Effects:     []Effect{},
		Image:       "Endrega-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         Special,
		Name:        "harpy",
		DisplayName: "Harpy",
		Strength:    2,
		Effects:     []Effect{Agile},
		Image:       "Harpy-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         RangedCombat,
		Name:        "cockatrice",
		DisplayName: "Cockatrice",
		Strength:    2,
		Effects:     []Effect{},
		Image:       "Cockatrice-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         RangedCombat,
		Name:        "gargoyle",
		DisplayName: "Gargoyle",
		Strength:    2,
		Effects:     []Effect{},
		Image:       "Gargoyle-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         Special,
		Name:        "celaeno-harpy",
		DisplayName: "Celaeno Harpy",
		Strength:    2,
		Effects:     []Effect{Agile},
		Image:       "Celaeno-Harpy-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         RangedCombat,
		Name:        "grave-hag",
		DisplayName: "Grave Hag",
		Strength:    5,
		Effects:     []Effect{},
		Image:       "Grave-Hag-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         Siege,
		Name:        "fire-elemental",
		DisplayName: "Fire Elemental",
		Strength:    6,
		Effects:     []Effect{},
		Image:       "Fire-Elemental-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "foglet",
		DisplayName: "Foglet",
		Strength:    2,
		Effects:     []Effect{},
		Image:       "Foglet-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         RangedCombat,
		Name:        "wyvern",
		DisplayName: "Wyvern",
		Strength:    2,
		Effects:     []Effect{},
		Image:       "Wyvern-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         Siege,
		Name:        "arachas-behemoth",
		DisplayName: "Arachas Behemoth",
		Strength:    6,
		Effects:     []Effect{Muster},
		Image:       "Arachas-Behemoth-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "arachas",
		DisplayName: "Arachas",
		Strength:    4,
		Effects:     []Effect{Muster},
		Image:       "Arachas-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "arachas",
		DisplayName: "Arachas",
		Strength:    4,
		Effects:     []Effect{Muster},
		Image:       "Arachas-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "arachas",
		DisplayName: "Arachas",
		Strength:    4,
		Effects:     []Effect{Muster},
		Image:       "Arachas-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "nekker",
		DisplayName: "Nekker",
		Strength:    2,
		Effects:     []Effect{Muster},
		Image:       "Nekker-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "nekker",
		DisplayName: "Nekker",
		Strength:    2,
		Effects:     []Effect{Muster},
		Image:       "Nekker-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "nekker",
		DisplayName: "Nekker",
		Strength:    2,
		Effects:     []Effect{Muster},
		Image:       "Nekker-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "vampire",
		DisplayName: "Vampire: Ekimmara",
		Strength:    4,
		Effects:     []Effect{Muster},
		Image:       "Vampire:-Ekimmara-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "vampire",
		DisplayName: "Vampire: Fleder",
		Strength:    4,
		Effects:     []Effect{Muster},
		Image:       "Vampire:-Fleder-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "vampire",
		DisplayName: "Vampire: Garkain",
		Strength:    4,
		Effects:     []Effect{Muster},
		Image:       "Vampire:-Garkain-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "vampire",
		DisplayName: "Vampire: Bruxa",
		Strength:    4,
		Effects:     []Effect{Muster},
		Image:       "Vampire:-Bruxa-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "vampire",
		DisplayName: "Vampire: Katakan",
		Strength:    5,
		Effects:     []Effect{Muster},
		Image:       "Vampire:-Katakan-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "ghoul",
		DisplayName: "Ghoul",
		Strength:    1,
		Effects:     []Effect{Muster},
		Image:       "Ghoul-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "ghoul",
		DisplayName: "Ghoul",
		Strength:    1,
		Effects:     []Effect{Muster},
		Image:       "Ghoul-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "ghoul",
		DisplayName: "Ghoul",
		Strength:    1,
		Effects:     []Effect{Muster},
		Image:       "Ghoul-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "crone",
		DisplayName: "Crone: Brewess",
		Strength:    6,
		Effects:     []Effect{Muster},
		Image:       "Crone:-Brewess-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "crone",
		DisplayName: "Crone: Weavess",
		Strength:    6,
		Effects:     []Effect{Muster},
		Image:       "Crone:-Weavess-gwent-card.jpg",
	},
	Card{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "crone",
		DisplayName: "Crone: Whispess",
		Strength:    6,
		Effects:     []Effect{Muster},
		Image:       "Crone:-Whispess-gwent-card.jpg",
	},
}
