package gwent

var AllCards = []Card{
	{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "geralt-of-rivia",
		DisplayName: "Geralt of Rivia",
		Strengh:     15,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "cirilla-fiona-elen-riannon",
		DisplayName: "Cirilla Fiona Elen Riannon",
		Strengh:     15,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "vesemir",
		DisplayName: "Vesemir",
		Strengh:     6,
		Effects:     []Effect{},
	},
	{
		Faction:     Neutral,
		Row:         RangedCombat,
		Name:        "yennefer-of-vengerberg",
		DisplayName: "Yennefer of Vengerberg",
		Strengh:     7,
		Effects:     []Effect{Medic, Hero},
	},
	{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "triss-merigold",
		DisplayName: "Triss Merigold",
		Strengh:     7,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "dandelion",
		DisplayName: "Dandelion",
		Strengh:     2,
		Effects:     []Effect{MoraleBoost},
	},
	{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "zoltan-chivay",
		DisplayName: "Zoltan Chivay",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "emiel-regis-rohellec-terzieff",
		DisplayName: "Emiel Regis Rohellec Terzieff",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "villentretenmerth",
		DisplayName: "Villentretenmerth",
		Strengh:     7,
		Effects:     []Effect{Scorch},
	},
	{
		Faction:     Neutral,
		Row:         CloseCombat,
		Name:        "avallac’h",
		DisplayName: "Avallac’h",
		Strengh:     0,
		Effects:     []Effect{Spy, Hero},
	},
	/*{
		Faction:     Neutral,
		Row:         Special,
		Name:        "decoy",
		DisplayName: "Decoy",
		Strengh:     0,
		Effects:     []Effect{Decoy},
	},
	{
		Faction:     Neutral,
		Row:         Special,
		Name:        "decoy",
		DisplayName: "Decoy",
		Strengh:     0,
		Effects:     []Effect{Decoy},
	},
	{
		Faction:     Neutral,
		Row:         Special,
		Name:        "decoy",
		DisplayName: "Decoy",
		Strengh:     0,
		Effects:     []Effect{Decoy},
	},*/
	{
		Faction:     Neutral,
		Row:         Special,
		Name:        "commander’s-horn",
		DisplayName: "Commander’s Horn",
		Strengh:     0,
		Effects:     []Effect{MoraleBoost},
	},
	{
		Faction:     Neutral,
		Row:         Special,
		Name:        "commander’s-horn",
		DisplayName: "Commander’s Horn",
		Strengh:     0,
		Effects:     []Effect{MoraleBoost},
	},
	{
		Faction:     Neutral,
		Row:         Special,
		Name:        "commander’s-horn",
		DisplayName: "Commander’s Horn",
		Strengh:     0,
		Effects:     []Effect{MoraleBoost},
	},
	{
		Faction:     Neutral,
		Row:         Special,
		Name:        "scorch",
		DisplayName: "Scorch",
		Strengh:     0,
		Effects:     []Effect{Scorch},
	},
	{
		Faction:     Neutral,
		Row:         Special,
		Name:        "scorch",
		DisplayName: "Scorch",
		Strengh:     0,
		Effects:     []Effect{Scorch},
	},
	{
		Faction:     Neutral,
		Row:         Special,
		Name:        "scorch",
		DisplayName: "Scorch",
		Strengh:     0,
		Effects:     []Effect{Scorch},
	},
	{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "biting-frost",
		DisplayName: "Biting Frost",
		Strengh:     0,
		Effects:     []Effect{BitingFrost},
	},
	{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "biting-frost",
		DisplayName: "Biting Frost",
		Strengh:     0,
		Effects:     []Effect{BitingFrost},
	},
	{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "biting-frost",
		DisplayName: "Biting Frost",
		Strengh:     0,
		Effects:     []Effect{BitingFrost},
	},
	{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "impenetrable-fog",
		DisplayName: "Impenetrable Fog",
		Strengh:     0,
		Effects:     []Effect{ImpenetrableFog},
	},
	{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "impenetrable-fog",
		DisplayName: "Impenetrable Fog",
		Strengh:     0,
		Effects:     []Effect{ImpenetrableFog},
	},
	{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "impenetrable-fog",
		DisplayName: "Impenetrable Fog",
		Strengh:     0,
		Effects:     []Effect{ImpenetrableFog},
	},
	{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "torrential-rain",
		DisplayName: "Torrential Rain",
		Strengh:     0,
		Effects:     []Effect{TorrentialRain},
	},
	{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "torrential-rain",
		DisplayName: "Torrential Rain",
		Strengh:     0,
		Effects:     []Effect{TorrentialRain},
	},
	{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "torrential-rain",
		DisplayName: "Torrential Rain",
		Strengh:     0,
		Effects:     []Effect{TorrentialRain},
	},
	{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "clear-weather",
		DisplayName: "Clear Weather",
		Strengh:     0,
		Effects:     []Effect{ClearWeather},
	},
	{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "clear-weather",
		DisplayName: "Clear Weather",
		Strengh:     0,
		Effects:     []Effect{ClearWeather},
	},
	{
		Faction:     Neutral,
		Row:         Weather,
		Name:        "clear-weather",
		DisplayName: "Clear Weather",
		Strengh:     0,
		Effects:     []Effect{ClearWeather},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "vernon-roche",
		DisplayName: "Vernon Roche",
		Strengh:     10,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "john-natalis",
		DisplayName: "John Natalis",
		Strengh:     10,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "esterad-thyssen",
		DisplayName: "Esterad Thyssen",
		Strengh:     10,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     NorthernRealms,
		Row:         RangedCombat,
		Name:        "philippa-eilhart",
		DisplayName: "Philippa Eilhart",
		Strengh:     10,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "thaler",
		DisplayName: "Thaler",
		Strengh:     1,
		Effects:     []Effect{Spy},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "ves",
		DisplayName: "Ves",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "siegfried-of-denesle",
		DisplayName: "Siegfried of Denesle",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "yarpen-zigrin",
		DisplayName: "Yarpen Zigrin",
		Strengh:     2,
		Effects:     []Effect{},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "sigismund-dijkstra",
		DisplayName: "Sigismund Dijkstra",
		Strengh:     4,
		Effects:     []Effect{Spy},
	},
	{
		Faction:     NorthernRealms,
		Row:         RangedCombat,
		Name:        "keira-metz",
		DisplayName: "Keira Metz",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     NorthernRealms,
		Row:         RangedCombat,
		Name:        "síle-de-tansarville",
		DisplayName: "Síle de Tansarville",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "sabrina-glevissig",
		DisplayName: "Sabrina Glevissig",
		Strengh:     4,
		Effects:     []Effect{},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "sheldon-skaggs",
		DisplayName: "Sheldon Skaggs",
		Strengh:     4,
		Effects:     []Effect{},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "dethmold",
		DisplayName: "Dethmold",
		Strengh:     6,
		Effects:     []Effect{},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "prince-stennis",
		DisplayName: "Prince Stennis",
		Strengh:     5,
		Effects:     []Effect{Spy},
	},
	{
		Faction:     NorthernRealms,
		Row:         RangedCombat,
		Name:        "trebuchet",
		DisplayName: "Trebuchet",
		Strengh:     6,
		Effects:     []Effect{},
	},
	{
		Faction:     NorthernRealms,
		Row:         RangedCombat,
		Name:        "trebuchet",
		DisplayName: "Trebuchet",
		Strengh:     6,
		Effects:     []Effect{},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "poor-f*cking-infantry",
		DisplayName: "Poor F*cking Infantry",
		Strengh:     1,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "poor-f*cking-infantry",
		DisplayName: "Poor F*cking Infantry",
		Strengh:     1,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "poor-f*cking-infantry",
		DisplayName: "Poor F*cking Infantry",
		Strengh:     1,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     NorthernRealms,
		Row:         RangedCombat,
		Name:        "crinfrid-reavers-dragon-hunter",
		DisplayName: "Crinfrid Reavers Dragon Hunter",
		Strengh:     5,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     NorthernRealms,
		Row:         RangedCombat,
		Name:        "crinfrid-reavers-dragon-hunter",
		DisplayName: "Crinfrid Reavers Dragon Hunter",
		Strengh:     5,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     NorthernRealms,
		Row:         RangedCombat,
		Name:        "crinfrid-reavers-dragon-hunter",
		DisplayName: "Crinfrid Reavers Dragon Hunter",
		Strengh:     5,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "redanian-foot-soldier",
		DisplayName: "Redanian Foot Soldier",
		Strengh:     1,
		Effects:     []Effect{},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "redanian-foot-soldier",
		DisplayName: "Redanian Foot Soldier",
		Strengh:     1,
		Effects:     []Effect{},
	},
	{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "catapult",
		DisplayName: "Catapult",
		Strengh:     8,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "catapult",
		DisplayName: "Catapult",
		Strengh:     8,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "ballista",
		DisplayName: "Ballista",
		Strengh:     6,
		Effects:     []Effect{},
	},
	{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "ballista",
		DisplayName: "Ballista",
		Strengh:     6,
		Effects:     []Effect{},
	},
	{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "kaedweni-siege-expert",
		DisplayName: "Kaedweni Siege Expert",
		Strengh:     1,
		Effects:     []Effect{MoraleBoost},
	},
	{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "kaedweni-siege-expert",
		DisplayName: "Kaedweni Siege Expert",
		Strengh:     1,
		Effects:     []Effect{MoraleBoost},
	},
	{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "kaedweni-siege-expert",
		DisplayName: "Kaedweni Siege Expert",
		Strengh:     1,
		Effects:     []Effect{MoraleBoost},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "blue-stripes-commando",
		DisplayName: "Blue Stripes Commando",
		Strengh:     4,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "blue-stripes-commando",
		DisplayName: "Blue Stripes Commando",
		Strengh:     4,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     NorthernRealms,
		Row:         CloseCombat,
		Name:        "blue-stripes-commando",
		DisplayName: "Blue Stripes Commando",
		Strengh:     4,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "siege-tower",
		DisplayName: "Siege Tower",
		Strengh:     6,
		Effects:     []Effect{},
	},
	{
		Faction:     NorthernRealms,
		Row:         Siege,
		Name:        "dun-banner-medic",
		DisplayName: "Dun Banner Medic",
		Strengh:     5,
		Effects:     []Effect{Medic},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "letho-of-gulet",
		DisplayName: "Letho of Gulet",
		Strengh:     10,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "menno-coehoorn",
		DisplayName: "Menno Coehoorn",
		Strengh:     10,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     Nilfgaard,
		Row:         Siege,
		Name:        "morvran-voorhis",
		DisplayName: "Morvran Voorhis",
		Strengh:     10,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "tibor-eggebracht",
		DisplayName: "Tibor Eggebracht",
		Strengh:     10,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "albrich",
		DisplayName: "Albrich",
		Strengh:     2,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "assire-var-anahid",
		DisplayName: "Assire var Anahid",
		Strengh:     6,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "cynthia",
		DisplayName: "Cynthia",
		Strengh:     4,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "fringilla-vigo",
		DisplayName: "Fringilla Vigo",
		Strengh:     6,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "morteisen",
		DisplayName: "Morteisen",
		Strengh:     3,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "rainfarn",
		DisplayName: "Rainfarn",
		Strengh:     4,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "renuald-aep-matsen",
		DisplayName: "Renuald aep Matsen",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         Siege,
		Name:        "rotten-mangonel",
		DisplayName: "Rotten Mangonel",
		Strengh:     3,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "shilard-fitz-oesterlen",
		DisplayName: "Shilard Fitz-Oesterlen",
		Strengh:     7,
		Effects:     []Effect{Spy},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "stefan-skellen",
		DisplayName: "Stefan Skellen",
		Strengh:     9,
		Effects:     []Effect{Spy},
	},
	{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "sweers",
		DisplayName: "Sweers",
		Strengh:     2,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "vanhemar",
		DisplayName: "Vanhemar",
		Strengh:     4,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "vattier-de-rideaux",
		DisplayName: "Vattier de Rideaux",
		Strengh:     4,
		Effects:     []Effect{Spy},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "vreemde",
		DisplayName: "Vreemde",
		Strengh:     2,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "cahir-mawr-dyffryn-aep-ceallach",
		DisplayName: "Cahir Mawr Dyffryn aep Ceallach",
		Strengh:     6,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "puttkammer",
		DisplayName: "Puttkammer",
		Strengh:     3,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "etolian-auxiliary-archers",
		DisplayName: "Etolian Auxiliary Archers",
		Strengh:     1,
		Effects:     []Effect{Medic},
	},
	{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "etolian-auxiliary-archers",
		DisplayName: "Etolian Auxiliary Archers",
		Strengh:     1,
		Effects:     []Effect{Medic},
	},
	{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "black-infantry-archer",
		DisplayName: "Black Infantry Archer",
		Strengh:     10,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         Siege,
		Name:        "siege-technican",
		DisplayName: "Siege Technican",
		Strengh:     0,
		Effects:     []Effect{Medic},
	},
	{
		Faction:     Nilfgaard,
		Row:         RangedCombat,
		Name:        "black-infantry-archer",
		DisplayName: "Black Infantry Archer",
		Strengh:     10,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         Siege,
		Name:        "heavy-zerrikanian-fire-scorpion",
		DisplayName: "Heavy Zerrikanian Fire Scorpion",
		Strengh:     10,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         Siege,
		Name:        "zerrikanian-fire-scorpion",
		DisplayName: "Zerrikanian Fire Scorpion",
		Strengh:     10,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "impera-brigade",
		DisplayName: "Impera Brigade",
		Strengh:     3,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "impera-brigade",
		DisplayName: "Impera Brigade",
		Strengh:     3,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "impera-brigade",
		DisplayName: "Impera Brigade",
		Strengh:     3,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "impera-brigade",
		DisplayName: "Impera Brigade",
		Strengh:     3,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "nausicaa-cavalry-brigade",
		DisplayName: "Nausicaa Cavalry Brigade",
		Strengh:     2,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "nausicaa-cavalry-brigade",
		DisplayName: "Nausicaa Cavalry Brigade",
		Strengh:     2,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "nausicaa-cavalry-brigade",
		DisplayName: "Nausicaa Cavalry Brigade",
		Strengh:     2,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     Nilfgaard,
		Row:         Siege,
		Name:        "siege-engineer",
		DisplayName: "Siege Engineer",
		Strengh:     6,
		Effects:     []Effect{},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "young-emissary",
		DisplayName: "Young Emissary",
		Strengh:     5,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     Nilfgaard,
		Row:         CloseCombat,
		Name:        "young-emissary",
		DisplayName: "Young Emissary",
		Strengh:     5,
		Effects:     []Effect{TightBond},
	},
	{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "eithné",
		DisplayName: "Eithné",
		Strengh:     10,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "saesenthessis",
		DisplayName: "Saesenthessis",
		Strengh:     10,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "isengrim-faoiltiarna",
		DisplayName: "Isengrim Faoiltiarna",
		Strengh:     10,
		Effects:     []Effect{MoraleBoost},
	},
	{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "iorveth",
		DisplayName: "Iorveth",
		Strengh:     10,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "dennis-cranmer",
		DisplayName: "Dennis Cranmer",
		Strengh:     6,
		Effects:     []Effect{},
	},
	{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "milva",
		DisplayName: "Milva",
		Strengh:     10,
		Effects:     []Effect{MoraleBoost},
	},
	{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "ida-emean",
		DisplayName: "Ida Emean",
		Strengh:     6,
		Effects:     []Effect{},
	},
	{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "filavandrel",
		DisplayName: "Filavandrel",
		Strengh:     6,
		Effects:     []Effect{Agile},
	},
	{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "yaevinn",
		DisplayName: "Yaevinn",
		Strengh:     6,
		Effects:     []Effect{Agile},
	},
	{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "toruviel",
		DisplayName: "Toruviel",
		Strengh:     2,
		Effects:     []Effect{},
	},
	{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "riordain",
		DisplayName: "Riordain",
		Strengh:     1,
		Effects:     []Effect{},
	},
	{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "ciaran-aep-easnillien",
		DisplayName: "Ciaran aep Easnillien",
		Strengh:     3,
		Effects:     []Effect{Agile},
	},
	{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "barclay-els",
		DisplayName: "Barclay Els",
		Strengh:     6,
		Effects:     []Effect{Agile},
	},
	{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "havekar-healer",
		DisplayName: "Havekar Healer",
		Strengh:     0,
		Effects:     []Effect{Medic},
	},
	{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "havekar-healer",
		DisplayName: "Havekar Healer",
		Strengh:     0,
		Effects:     []Effect{Medic},
	},
	{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "havekar-healer",
		DisplayName: "Havekar Healer",
		Strengh:     0,
		Effects:     []Effect{Medic},
	},
	{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "vrihedd-brigade-veteran",
		DisplayName: "Vrihedd Brigade Veteran",
		Strengh:     5,
		Effects:     []Effect{Agile},
	},
	{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "vrihedd-brigade-veterean",
		DisplayName: "Vrihedd Brigade Veterean",
		Strengh:     5,
		Effects:     []Effect{Agile},
	},
	{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "dol-blathanna-archer",
		DisplayName: "Dol Blathanna Archer",
		Strengh:     6,
		Effects:     []Effect{Agile},
	},
	{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "dol-blathanna-scout",
		DisplayName: "Dol Blathanna Scout",
		Strengh:     6,
		Effects:     []Effect{Agile},
	},
	{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "dol-blathanna-scout",
		DisplayName: "Dol Blathanna Scout",
		Strengh:     6,
		Effects:     []Effect{Agile},
	},
	{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "dwarf-skirmisher",
		DisplayName: "Dwarf Skirmisher",
		Strengh:     3,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "dwarf-skirmisher",
		DisplayName: "Dwarf Skirmisher",
		Strengh:     3,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "dwarf-skirmisher",
		DisplayName: "Dwarf Skirmisher",
		Strengh:     3,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "mahakaman-defender",
		DisplayName: "Mahakaman Defender",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "mahakaman-defender",
		DisplayName: "Mahakaman Defender",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "mahakaman-defender",
		DisplayName: "Mahakaman Defender",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "mahakaman-defender",
		DisplayName: "Mahakaman Defender",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "mahakaman-defender",
		DisplayName: "Mahakaman Defender",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "elven-skirmisher",
		DisplayName: "Elven Skirmisher",
		Strengh:     2,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "elven-skirmisher",
		DisplayName: "Elven Skirmisher",
		Strengh:     2,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "elven-skirmisher",
		DisplayName: "Elven Skirmisher",
		Strengh:     2,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     ScoiaTael,
		Row:         Special,
		Name:        "vrihedd-cadet",
		DisplayName: "Vrihedd Cadet",
		Strengh:     4,
		Effects:     []Effect{},
	},
	{
		Faction:     ScoiaTael,
		Row:         RangedCombat,
		Name:        "dol-blathanna-archer",
		DisplayName: "Dol Blathanna Archer",
		Strengh:     4,
		Effects:     []Effect{},
	},
	{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "havekar-smuggler",
		DisplayName: "Havekar Smuggler",
		Strengh:     5,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "havekar-smuggler",
		DisplayName: "Havekar Smuggler",
		Strengh:     5,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     ScoiaTael,
		Row:         CloseCombat,
		Name:        "havekar-smuggler",
		DisplayName: "Havekar Smuggler",
		Strengh:     5,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "draug",
		DisplayName: "Draug",
		Strengh:     10,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     Monsters,
		Row:         Special,
		Name:        "kayran",
		DisplayName: "Kayran",
		Strengh:     18,
		Effects:     []Effect{MoraleBoost, Agile, Hero},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "imlerith",
		DisplayName: "Imlerith",
		Strengh:     10,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     Monsters,
		Row:         RangedCombat,
		Name:        "leshen",
		DisplayName: "Leshen",
		Strengh:     10,
		Effects:     []Effect{Hero},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "forktail",
		DisplayName: "Forktail",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     Monsters,
		Row:         Siege,
		Name:        "earth-elemental",
		DisplayName: "Earth Elemental",
		Strengh:     6,
		Effects:     []Effect{},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "fiend",
		DisplayName: "Fiend",
		Strengh:     6,
		Effects:     []Effect{},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "plague-maiden",
		DisplayName: "Plague Maiden",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "griffin",
		DisplayName: "Griffin",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "werewolf",
		DisplayName: "Werewolf",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "botchling",
		DisplayName: "Botchling",
		Strengh:     4,
		Effects:     []Effect{},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "frightener",
		DisplayName: "Frightener",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     Monsters,
		Row:         Siege,
		Name:        "ice-giant",
		DisplayName: "Ice Giant",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     Monsters,
		Row:         RangedCombat,
		Name:        "endrega",
		DisplayName: "Endrega",
		Strengh:     2,
		Effects:     []Effect{},
	},
	{
		Faction:     Monsters,
		Row:         Special,
		Name:        "harpy",
		DisplayName: "Harpy",
		Strengh:     2,
		Effects:     []Effect{Agile},
	},
	{
		Faction:     Monsters,
		Row:         RangedCombat,
		Name:        "cockatrice",
		DisplayName: "Cockatrice",
		Strengh:     2,
		Effects:     []Effect{},
	},
	{
		Faction:     Monsters,
		Row:         RangedCombat,
		Name:        "gargoyle",
		DisplayName: "Gargoyle",
		Strengh:     2,
		Effects:     []Effect{},
	},
	{
		Faction:     Monsters,
		Row:         Special,
		Name:        "celaeno-harpy",
		DisplayName: "Celaeno Harpy",
		Strengh:     2,
		Effects:     []Effect{Agile},
	},
	{
		Faction:     Monsters,
		Row:         RangedCombat,
		Name:        "grave-hag",
		DisplayName: "Grave Hag",
		Strengh:     5,
		Effects:     []Effect{},
	},
	{
		Faction:     Monsters,
		Row:         Siege,
		Name:        "fire-elemental",
		DisplayName: "Fire Elemental",
		Strengh:     6,
		Effects:     []Effect{},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "foglet",
		DisplayName: "Foglet",
		Strengh:     2,
		Effects:     []Effect{},
	},
	{
		Faction:     Monsters,
		Row:         RangedCombat,
		Name:        "wyvern",
		DisplayName: "Wyvern",
		Strengh:     2,
		Effects:     []Effect{},
	},
	{
		Faction:     Monsters,
		Row:         Siege,
		Name:        "arachas-behemoth",
		DisplayName: "Arachas Behemoth",
		Strengh:     6,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "arachas",
		DisplayName: "Arachas",
		Strengh:     4,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "arachas",
		DisplayName: "Arachas",
		Strengh:     4,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "arachas",
		DisplayName: "Arachas",
		Strengh:     4,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "nekker",
		DisplayName: "Nekker",
		Strengh:     2,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "nekker",
		DisplayName: "Nekker",
		Strengh:     2,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "nekker",
		DisplayName: "Nekker",
		Strengh:     2,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "vampire",
		DisplayName: "Vampire: Ekimmara",
		Strengh:     4,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "vampire",
		DisplayName: "Vampire: Fleder",
		Strengh:     4,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "vampire",
		DisplayName: "Vampire: Garkain",
		Strengh:     4,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "vampire",
		DisplayName: "Vampire: Bruxa",
		Strengh:     4,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "vampire",
		DisplayName: "Vampire: Katakan",
		Strengh:     5,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "ghoul",
		DisplayName: "Ghoul",
		Strengh:     1,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "ghoul",
		DisplayName: "Ghoul",
		Strengh:     1,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "ghoul",
		DisplayName: "Ghoul",
		Strengh:     1,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "crone",
		DisplayName: "Crone: Brewess",
		Strengh:     6,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "crone",
		DisplayName: "Crone: Weavess",
		Strengh:     6,
		Effects:     []Effect{Muster},
	},
	{
		Faction:     Monsters,
		Row:         CloseCombat,
		Name:        "crone",
		DisplayName: "Crone: Whispess",
		Strengh:     6,
		Effects:     []Effect{Muster},
	},
}

var AllCardsMap map[string]*Card

func init() {
	AllCardsMap = map[string]*Card{}
	for key, card := range AllCards {
		c := AllCards[key]
		AllCardsMap[card.Name] = &c
	}
}
